module.exports = {
    descriptors: [
      'Majestic',
      'Enchanting',
      'Whispering',
      'Serenade',
      'Royal',
      'Blissful',
      'Tranquil',
      'Golden',
      'Emerald',
      'Sacred',
      'Mystic',
      'Spice',
      'Silk',
      'Lotus',
      'Karma',
      'Divine',
      'Dazzling',
      'Vibrant',
      'Breathtaking',
      'Enlightened',
      'Forest',
      'Ancient',
      'Petrified',
      'Roaring',
      'Cascade',
      'Tumbling',
      'Silent',
      'Redwood',
      'Bullfrog',
      'Maple',
      'Misty',
      'Elk',
      'Grizzly',
      'Ocean',
      'Sea',
      'Sky',
      'Dusty',
      'Diamond'
    ],
    places: [
      'Jungle',
      'Valley',
      'Lake',
      'Hills',
      'Retreat',
      'Sanctuary',
      'Oasis',
      'Shores',
      'Meadows',
      'Gardens',
      'Ridge',
      'Waterfall',
      'Beach',
      'Cave',
      'Plateau',
      'Heritage',
      'Spirit',
      'Enclave',
      'Trails',
      'Highlands',
      'Hideaway',
      'Flats',
      'Village',
      'Canyon',
      'Pond',
      'Group Camp',
      'Horse Camp',
      'Ghost Town',
      'Camp',
      'Dispersed Camp',
      'Backcountry',
      'River',
      'Creek',
      'Creekside',
      'Bay',
      'Spring',
      'Bayshore',
      'Sands',
      'Mule Camp',
      'Hunting Camp',
      'Cliffs',
      'Hollow'
    ],
    descriptions:[
      "Immerse yourself in nature's embrace at this serene campground.Camp under the starlit sky, explore scenic trails, and unwind by the campfire. Experience the perfect getaway surrounded by natural beauty.",
      "Discover the beauty of this tranquil campground nestled amidst breathtaking landscapes. Enjoy outdoor activities, connect with nature, and create unforgettable memories. Find your peaceful escape in this idyllic setting.",
      "Experience the ultimate outdoor adventure at this picturesque campground. Hike through scenic trails, indulge in water activities, and relax in nature's embrace. Unwind and rejuvenate amidst serene surroundings.",
      "Escape to this hidden gem surrounded by natural wonders. Camp amidst lush forests, discover hidden trails, and immerse yourself in the beauty of the great outdoors. Create unforgettable moments in this tranquil haven.",
      "Unwind in the beauty of this nature retreat. Immerse yourself in outdoor activities, enjoy breathtaking views, and rejuvenate your soul. Connect with nature and find serenity in this idyllic campground.",
      "Embark on an adventure at this captivating campground. Surround yourself with stunning landscapes, engage in thrilling outdoor activities, and create lifelong memories. Discover the perfect blend of adventure and relaxation in this nature lover's paradise.",
      "Immerse yourself in the tranquility of this enchanting campground. Explore scenic trails, indulge in outdoor recreation, and embrace the peaceful ambiance. Experience the beauty of nature and find solace in this idyllic retreat.",
      "Discover a hidden oasis at this charming campground. Camp beneath starry skies, enjoy panoramic views, and engage in outdoor pursuits. Escape the hustle and bustle and reconnect with nature in this serene haven.",
      "Experience nature's playground at this captivating campground. Engage in thrilling adventures, witness breathtaking vistas, and unwind amidst pristine surroundings. Find your bliss and create unforgettable memories in this outdoor paradise.",
      "Journey to this scenic campground and immerse yourself in nature's wonders. Explore picturesque trails, enjoy tranquil moments by the campfire, and marvel at the beauty that surrounds you. Find your escape in this captivating natural haven."
    ]
  };
  